######################################################################
# Automatically generated by qmake (2.01a) lun. avr. 11 11:04:53 2011
######################################################################

DESTDIR = ../build
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwidget.h \
    liste.h \
    node.h \
    bike.h \
    game.h
SOURCES += main.cpp mainwidget.cpp \
    liste.cpp \
    node.cpp \
    bike.cpp \
    game.cpp

#je rajoute
#CONFIG +=  console debug

